options:
	path: (join ("..", "..", "..", "..", "..", "..", "src", "test", "skript", "tests" and "") by file_separator())

test "script name (old)":
	set {_name} to the script's name
	assert the script's name is {@path} + "misc" + file_separator() + "legacy script name" with "script name is wrong"
	# Original behaviour included the file path and name but not the extension, e.g. `quests/MyQuestScript`
