test "join strings":
	assert join "a", "b" and "c" is "abc" with "join strings without delimiter failed"
	assert join "a", "b" and "c" with " " is "a b c" with "join strings with delimiter failed"

test "split strings on string":
	assert split "abc" at "[a-z]" is "abc" with "split with regex chars failed"

	assert split "a b c" at " " is "a", "b" and "c" with "split failed"
	assert split "a b c" at " " with case sensitivity is "a", "b" and "c" with "split with case sensitivity failed"
	assert split "a b c" at " " without trailing string is "a", "b" and "c" with "split without trailing string failed"

	assert split "abc" at "" is "a", "b", "c" and "" with "split with empty delimiter failed"
	assert split "abc" at "" with case sensitivity is "a", "b", "c" and "" with "split with empty delimiter with case sensitivity failed"
	assert split "abc" at "" without trailing string is "a", "b" and "c" with "split with empty delimiter without trailing string failed"
	assert split "abc" at "" with case sensitivity without trailing string is "a", "b" and "c" with "split with empty delimiter with case sensitivity without trailing string failed"

	assert split "-x-X" at "x" is "-", "-" and "" with "split with delimiter at end failed"
	assert split "-x-X" at "x" with case sensitivity is "-" and "-X" with "split with delimiter at end with case sensitivity failed"
	assert split "-x-X" at "x" without trailing string is "-" and "-" with "split with delimiter at end without trailing string failed"
	assert split "-x-X" at "x" with case sensitivity without trailing string is "-" and "-X" with "split with delimiter at end with case sensitivity without trailing string failed"

test "split strings on regex":
	assert regex split "a b c" at " " is "a", "b" and "c" with "regex split failed"
	assert regex split "a b_c" at "( |_)" is "a", "b" and "c" with "regex split with regex failed"

	assert regex split "-a-b-c" at "[a-z]" is "-", "-", "-" and "" with "regex split with delimiter at end failed"
	assert regex split "-a-b-c" at "[a-z]" without trailing string is "-", "-" and "-" with "regex split with delimiter at end without trailing string failed"
