test "display interpolation":

	spawn block display at spawn of world "world":
		set {_e::1} to entity
	spawn item display at spawn of world "world":
		set {_e::2} to entity
	spawn text display at spawn of world "world":
		set {_e::3} to entity

	assert interpolation delay of {_e::*} is 0 ticks with "default delay was not 0"
	assert interpolation duration of {_e::*} is 0 seconds with "default duration was not 0"

	set interpolation delay of {_e::*} to 5 ticks
	assert interpolation delay of {_e::*} is 5 ticks with "failed to set to delay"
	assert interpolation duration of {_e::*} is 0 seconds with "setting height modified duration"

	set interpolation duration of {_e::*} to 0.1 seconds
	assert interpolation delay of {_e::*} is 5 ticks with "setting width modified delay"
	assert interpolation duration of {_e::*} is 0.1 seconds with "failed to set to duration"

	set interpolation delay of {_e::*} to 0 ticks
	assert interpolation delay of {_e::*} is 0 ticks with "set to delay to 0 value"

	add 20 ticks to interpolation delay of {_e::*}
	assert interpolation delay of {_e::*} is 20 ticks with "add 20 to delay"

	subtract 25 ticks from interpolation delay of {_e::*}
	assert interpolation delay of {_e::*} is 0 ticks with "subtract 25 from delay"

	reset interpolation delay of {_e::*}
	assert interpolation delay of {_e::*} is 0 seconds with "reset delay"

	delete entities within {_e::*}
