test "block sounds (1.20+)":

	# === SETUP ===

	set {_before} to blockdata of (block at (spawn of world "world"))
	set {_20} to whether running minecraft "1.20"
	set {_empty} to "INTENTIONALLY_EMPTY" if running minecraft "1.20" else "BLOCK.STONE.PLACE"

	# === TESTS ===

	set {_stone::*} to getObjects(stone)
	assert break sound of {_stone::*} is "BLOCK.STONE.BREAK" with "break sound of stone wasn't BLOCK.STONE.BREAK"
	assert fall sound of {_stone::*} is "BLOCK.STONE.FALL" with "fall sound of stone wasn't BLOCK.STONE.FALL"
	assert hit sound of {_stone::*} is "BLOCK.STONE.HIT" with "hit sound of stone wasn't BLOCK.STONE.HIT"
	assert place sound of {_stone::*} is "BLOCK.STONE.PLACE" with "place sound of stone wasn't BLOCK.STONE.PLACE"
	assert step sound of {_stone::*} is "BLOCK.STONE.STEP" with "step sound of stone wasn't BLOCK.STONE.STEP"

	set {_wool::*} to getObjects(white wool)
	assert break sound of {_wool::*} is "BLOCK.WOOL.BREAK" with "break sound of stone wasn't BLOCK.WOOL.BREAK"
	assert fall sound of {_wool::*} is "BLOCK.WOOL.FALL" with "fall sound of stone wasn't BLOCK.WOOL.FALL"
	assert hit sound of {_wool::*} is "BLOCK.WOOL.HIT" with "hit sound of stone wasn't BLOCK.WOOL.HIT"
	assert place sound of {_wool::*} is "BLOCK.WOOL.PLACE" with "place sound of stone wasn't BLOCK.WOOL.PLACE"
	assert step sound of {_wool::*} is "BLOCK.WOOL.STEP" with "step sound of stone wasn't BLOCK.WOOL.STEP"

	assert break sound of (water, lava and bubble column) is ("INTENTIONALLY_EMPTY" if {_20} is true else "BLOCK.STONE.BREAK") with "break sound of water, lava, or bubble column wasn't INTENTIONALLY_EMPTY"
	assert fall sound of (water, lava and bubble column) is ("INTENTIONALLY_EMPTY" if {_20} is true else "BLOCK.STONE.FALL") with "fall sound of water, lava, or bubble column wasn't INTENTIONALLY_EMPTY"
	assert hit sound of (water, lava and bubble column) is ("INTENTIONALLY_EMPTY" if {_20} is true else "BLOCK.STONE.HIT") with "hit sound of water, lava, or bubble column wasn't INTENTIONALLY_EMPTY"
	assert place sound of (water, lava and bubble column) is ("INTENTIONALLY_EMPTY" if {_20} is true else "BLOCK.STONE.PLACE") with "place sound of water, lava, or bubble column wasn't INTENTIONALLY_EMPTY"
	assert step sound of (water, lava and bubble column) is ("INTENTIONALLY_EMPTY" if {_20} is true else "BLOCK.STONE.STEP") with "step sound of water, lava, or bubble column wasn't INTENTIONALLY_EMPTY"

	assert break sound of (diamond, diamond sword and {_none}) is not set with "break sound of non-block item shouldn't be set"
	assert fall sound of (diamond, diamond sword and {_none}) is not set with "fall sound of non-block item shouldn't be set"
	assert hit sound of (diamond, diamond sword and {_none}) is not set with "hit sound of non-block item shouldn't be set"
	assert place sound of (diamond, diamond sword and {_none}) is not set with "place sound of non-block item shouldn't be set"
	assert step sound of (diamond, diamond sword and {_none}) is not set with "step sound of non-block item shouldn't be set"

	# === CLEANUP ===

	set blockdata of {_block} to {_before}

local function getObjects(i: itemtype) :: objects:
	if (block at (spawn of world "world")) is not {_i}:
		set block at (spawn of world "world") to {_i}
	set {_block} to block at (spawn of world "world")
	set {_data} to blockdata of {_block}
	return {_block}, {_data} and {_i}
