test "block data":
	set {_b} to block at test-location
	set block at {_b} to campfire[lit=false;waterlogged=true]
	assert block at {_b} is campfire[lit=false] with "block at spawn should be an unlit campfire"

	assert block at {_b} = campfire[lit=false;waterlogged=true] with "block should have been an unlit, waterlogged campfire"
	assert block at {_b} = campfire[waterlogged=true] with "block should have been a waterlogged campfire"
	assert block at {_b} = campfire[] with "block should have been a campfire"
	assert block at {_b} != campfire[lit=true;waterlogged=false] with "block should not have been an unlit, waterlogged campfire"

	set {_data} to block data of block at {_b}
	assert "%{_data}%" contains "campfire", "lit=false" and "waterlogged=true" with "block data for campfire did not match"

	set block at {_b} to air

test "falling block block data":
    spawn a falling block at test-location:
        set {_e} to entity
    assert block data of {_e} is stone[] with "Falling block should default to stone"
    set block data of {_e} to sand[]
    assert block data of {_e} is sand[] with "Falling block should update to sand"
    clear entity within {_e}
