test "brewing slots":
	set {_old} to test-block
	set test-block to brewing stand

	set the brewing stand first bottle slot of test-block to potion of water
	assert the brewing stand first bottle slot of test-block is potion of water with "First Bottle Slot was not set"
	set the brewing stand second bottle slot of test-block to glass bottle
	assert the brewing stand second bottle slot of test-block is glass bottle with "Second Bottle Slot was not set"
	set the brewing stand third bottle slot of test-block to speed potion
	assert the brewing stand third bottle slot of test-block is speed potion with "Third Bottle Slot was not set"
	set the brewing stand fuel slot of test-block to blaze powder
	assert the brewing stand fuel slot of test-block is blaze powder with "Fuel Slot was not set"
	set the brewing stand ingredient slot of test-block to nether wart
	assert the brewing stand ingredient slot of test-block is nether wart with "Ingredient slot was not set"

	set test-block to {_old}
