test "spawner type":
	set test-block to spawner
	set {_block} to test-block

	set spawner type of {_block} to zombie
	assert spawner type of {_block} is zombie with "Spawner type was set to a Zombie"

	reset spawner type of {_block}
	assert spawner type of {_block} is pig with "Spawner type was not reset correctly"

	set block at {_block} to air

test "trial spawner type" when running minecraft "1.21":
	set test-block to trial spawner
	set {_block} to test-block

	set spawner type of {_block} to zombie
	assert spawner type of {_block} is zombie with "Spawner type was set to a Zombie"

	reset spawner type of {_block}
	assert spawner type of {_block} is pig with "Spawner type was not reset correctly"

	set block at {_block} to air

test "delete spawner type" when running minecraft "1.20.0":
	set test-block to spawner
	set the spawner type of test-block to a trader llama
	assert the spawner type of test-block is a trader llama with "Spawner type should be a trader llama"
	clear the spawner type of test-block
	assert the spawner type of test-block is not set with "Spawner type was not cleared"
	set test-block to air
