test "item amount fixes":
	set time in world "world" to night # we dont want our poor zombie to die
	spawn a zombie at test-location
	set {_e} to last spawned zombie

	set {_e}'s tool to dirt
	assert item amount of {_e}'s tool = 1 with "Item amount of Zombie's tool should have been 1"
	set item amount of {_e}'s tool to 10
	assert item amount of {_e}'s tool = 10 with "Item amount of Zombie's tool should have been 10"
	kill {_e} # ok maybe we do want him to die

	set time in world "world" to day

	drop dirt at location 20 above test-location
	set {_d} to last dropped item
	assert item amount of item of {_d} = 1 with "Item amount of dirt should have been 1"
	set item amount of item of {_d} to 10
	assert item amount of item of {_d} = 10 with "Item amount of dirt should have been 10"
	kill {_d}
