
# Test not related to a made issue. Details at pull request.
test "100 blocks fix":
	set {_l} to test-location ~ vector(0, -1, 10)
	set block at {_l} to air

	set {_blocks::*} to (block at {_l}), (block at {_l} ~ vector(0, -1, 0)), (block at {_l} ~ vector(0, -2, 0)), (block at {_l} ~ vector(0, -3, 0)), (block at {_l} ~ vector(0, -4, 0)), and (block at {_l} ~ vector(0, -5, 0))
	assert blocks 5 below {_l} is {_blocks::*} with "Failed to get correct blocks"
	assert size of blocks 3 below location below {_l} is 4 with "Failed to match asserted size"
