test "expressions sometimes dont convert":
	assert formatted ({_foo} + {_bar}) is not set with "formatting nothing shouldn't throw an error"

	set {_foo} to "test"
	assert formatted ({_foo} + {_bar}) is not set with "formatting string + none shouldn't throw an error"

	set {_foo} to 1
	set {_bar} to 2
	assert formatted ({_foo} + {_bar}) is not set with "formatting number + number shouldn't throw an error"

	set {_foo} to "foo"
	set {_bar} to "bar"
	assert formatted ({_foo} + {_bar}) is "foobar" with "formatting strings doesn't work"
