local function test(x: object) -> object:
    return {_x}

local function test2(x: object, minecraft: object) -> object:
    return {_minecraft}

local function test_same(minecraft: object) -> object:
    return {_minecraft}

test "fully qualified names and named argument functions conflict":
    assert test(minecraft:plains) is minecraft:plains
    assert test(minecraft:stone) is minecraft:stone
    assert test(minecraft:stone) is stone
    assert test(x: minecraft:stone) is minecraft:stone
    assert test(x: minecraft:stone) is stone
    parse:
        assert test(minecraft: stone) is minecraft:stone
    assert last parse logs are set

    assert test_same(stone) is minecraft:stone
    assert test_same(minecraft:stone) is minecraft:stone
    assert test_same(minecraft:minecraft:stone) is minecraft:stone
    assert test_same(minecraft:minecraft:plains) is minecraft:plains

    assert test2(x: minecraft:stone, minecraft:minecraft:plains) is minecraft:plains
    assert test2(minecraft:minecraft:plains, x: minecraft:stone) is minecraft:plains

    parse:
        assert test(minecraft: minecraft: stone) is minecraft:stone
    assert last parse logs are set

    assert test(x: 10) is 10
    assert test_same(minecraft:10) is 10


local function teststr(x: text) -> text:
    return {_x}

test "expression in string and named function arguments conflict":
	set {_now} to now
	assert test("%{_now} formatted as "HH:mm:ss"%") is {_now} formatted as "HH:mm:ss"
