test "median function":
	assert median(1, 2, 3, 4, 5) = 3 with "median should be 3"
	assert median(1, 2, 3, 4, 5, 6) = 3.5 with "median should be 3.5"
	loop 10 times:
		add (10 * loop-iteration) to {_ints::*}
	assert median({_ints::*}) = 55 with "median should be 55"

	assert median(0, 1, 2, infinity value) is 1.5 with "median should return 1.5 even when providing infinity"
	assert median(0, 1, 2, nan value) is not set with "median should return null when providing nan"
