options:
	test: "org.skriptlang.skript.test.tests.syntaxes.events.EvtGrowTest"

on script load:
	# itemtype
	ensure junit test {@test} completes "grow of wheat"
	ensure junit test {@test} completes "grow from wheat"
	ensure junit test {@test} completes "grow to wheat"

	# blockdata
	ensure junit test {@test} completes "grow of wheat (blockdata)"
	ensure junit test {@test} completes "grow from wheat (blockdata)"
	ensure junit test {@test} completes "grow to wheat (blockdata)"

	# structures
	ensure junit test {@test} completes "grow of birch tree"
	ensure junit test {@test} completes "grow of birch sapling"
	ensure junit test {@test} completes "grow from birch sapling"
	ensure junit test {@test} completes "grow to birch tree"

on grow of wheat:
	junit test is {@test}
	complete objective "grow of wheat" for junit test {@test}

on grow of wheat[age=0]:
	junit test is {@test}
	complete objective "grow of wheat (blockdata)" for junit test {@test}

on grow from wheat:
	junit test is {@test}
	complete objective "grow from wheat" for junit test {@test}

on grow from wheat[age=0]:
	junit test is {@test}
	complete objective "grow from wheat (blockdata)" for junit test {@test}

on grow to wheat:
	junit test is {@test}
	complete objective "grow to wheat" for junit test {@test}

on grow to wheat[age=7]:
	junit test is {@test}
	complete objective "grow to wheat (blockdata)" for junit test {@test}

on grow of birch tree:
	junit test is {@test}
	complete objective "grow of birch tree" for junit test {@test}

on grow of birch sapling:
	junit test is {@test}
	complete objective "grow of birch sapling" for junit test {@test}

on grow from birch sapling:
	junit test is {@test}
	complete objective "grow from birch sapling" for junit test {@test}

on grow to birch tree:
	junit test is {@test}
	complete objective "grow to birch tree" for junit test {@test}
