test "explode creeper effect/condition":
	spawn a creeper at test-location
	assert last spawned creeper is not going to explode with "creepers should not explode when they are first spawned"
	start ignition of the last spawned creeper
	assert last spawned creeper is going to explode with "creepers should explode when the ignition process is started"
	stop ignition of the last spawned creeper
	assert last spawned creeper is not going to explode with "creepers should not explode when the ignition process is stopped"
	delete the last spawned creeper
